global:
  imageRegistry: ""
  imageTag: "latest"

frontend:
  repository: "snaplink-web"
  servicePort: 80

api:
  repository: "snaplink-api"
  servicePort: 5000

db:
  repository: "snaplink-db"
  servicePort: 5432
  user: ""
  password: ""
  name: "urlshort"

redis:
  repository: "snaplink-cache"
  servicePort: 6379


