apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.api.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.api.servicePort }}
          env:
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.db.user }}:{{ .Values.db.password }}@db:{{ .Values.db.servicePort }}/{{ .Values.db.name }}"
            - name: REDIS_URL
              value: "redis://redis:{{ .Values.redis.servicePort }}/0"
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.servicePort }}
