apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.db.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.db.servicePort }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: snaplink-db-creds
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: snaplink-db-creds
                  key: password
            - name: POSTGRES_DB
              value: "{{ .Values.db.name }}"
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: {{ .Values.db.servicePort }}
      targetPort: {{ .Values.db.servicePort }}
