apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        app: {{ .Values.redis.nodeSelectorLabel }}
      containers:
        - name: redis
          image: "{{ .Values.global.imageRegistry }}/{{ .Values.redis.repository }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.redis.servicePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
