apiVersion: v1
kind: Secret
metadata:
  name: snaplink-db-creds
  labels:
    app: db
type: Opaque
data:
  # The values are base64 encoded by Helm during deployment
  username: {{ .Values.db.user | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}
