{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: snaplink-db-creds
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ .Values.nameOverride | default .Release.Name }}
type: Opaque
data:
  username: {{ .Values.db.user | b64enc | quote }}
  password: {{ .Values.db.password | b64enc | quote }}
{{- end }}
