pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa','uat', 'prod', 'dr'], description: 'Select the target environment')
    }

    environment {
        SUB_CRED_ID         = "subscription_id_${params.ENVIRONMENT}"
        // Azure Credentials for Login
        ARM_CLIENT_ID       = credentials('aks_sp_client_id')
        ARM_CLIENT_SECRET   = credentials('aks_sp_secret')
        ARM_TENANT_ID       = credentials('aks_sp_tenant_id')
        ARM_SUBSCRIPTION_ID = credentials("${env.SUB_CRED_ID}")
        // Database Credentials
        DB_USER          = credentials('db_user')
        DB_PASS          = credentials('db_password')
        // Infrastructure parameters
        ACR_NAME         = "helmdeploymentapp${params.ENVIRONMENT}acr"
        AKS_CLUSTER_NAME = "helm-deployment-app-${params.ENVIRONMENT}-aks"
        RESOURCE_GROUP   = "helm-deployment-app-${params.ENVIRONMENT}-rg"
        IMAGE_TAG        = "${env.BUILD_NUMBER}"
    }

    stages {
        stage('Azure Login') {
            steps {
                sh """
                    az login --service-principal \
                        --username "${env.ARM_CLIENT_ID}" \
                        --password "${env.ARM_CLIENT_SECRET}" \
                        --tenant "${env.ARM_TENANT_ID}"

                    az account set --subscription "${env.ARM_SUBSCRIPTION_ID}"
                """
            }
        }
        
        stage('Get AKS Credentials') {
            steps {
                sh "az aks get-credentials --resource-group ${RESOURCE_GROUP} --name ${AKS_CLUSTER_NAME} --overwrite-existing"
            }
        }

        stage('ACR Login') {
            steps {
                sh "az acr login --name ${ACR_NAME}"
            }
        }

        stage('Build & Push Images') {
            steps {
                script {
                    def services = [
                        'frontend': 'snaplink-web',
                        'api'     : 'snaplink-api',
                        'db'      : 'snaplink-db',
                        'cache'   : 'snaplink-cache'
                    ]

                    services.each { dir, repo ->
                        buildAndPushImage(dir, repo, env.ACR_NAME, env.IMAGE_TAG)
                    }
                }
            }
        }

        stage('Deploy Helm Chart') {
            steps {
                sh """
                    helm upgrade --install snaplink kube/snaplink \
                        --namespace default \
                        --set global.imageRegistry=${ACR_NAME}.azurecr.io \
                        --set global.imageTag=${IMAGE_TAG} \
                        --set db.user=${DB_USER} \
                        --set db.password=${DB_PASS}
                """
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo "Application pipeline deployed successfully."
        }
        failure {
            echo "Application pipeline failed."
        }
    }
}

// Function to build and push docker images
def buildAndPushImage(String dir, String repo, String acrName, String tag) {
    echo "Building and pushing ${repo}..."
    sh """
        docker build -t ${acrName}.azurecr.io/${repo}:${tag} src/${dir}
        docker push ${acrName}.azurecr.io/${repo}:${tag}
    """
}
