pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa','uat', 'prod', 'dr'], description: 'Select the target environment')
    }

    environment {
        ARM_CLIENT_ID       = credentials('aks_sp_client_id')
        ARM_CLIENT_SECRET   = credentials('aks_sp_secret')
        ARM_TENANT_ID       = credentials('aks_sp_tenant_id')
        
        DB_USER             = credentials('db_user')
        DB_PASS             = credentials('db_password')
        
        ARM_SUBSCRIPTION_ID = credentials("subscription_id_${params.ENVIRONMENT ?: 'dev'}")
        
        ACR_NAME            = "helmdeploymentapp${params.ENVIRONMENT ?: 'dev'}acr"
        AKS_CLUSTER_NAME    = "helm-deployment-app-${params.ENVIRONMENT ?: 'dev'}-aks"
        RESOURCE_GROUP      = "helm-deployment-app-${params.ENVIRONMENT ?: 'dev'}-rg"
        
        IMAGE_TAG           = "${BUILD_NUMBER ?: 'latest'}"
    }

    stages {
        stage('Azure Login') {
            steps {
                sh """
                    az login --service-principal \
                        --username "${env.ARM_CLIENT_ID}" \
                        --password "${env.ARM_CLIENT_SECRET}" \
                        --tenant "${env.ARM_TENANT_ID}"

                    az account set --subscription "${env.ARM_SUBSCRIPTION_ID}"
                """
            }
        }
        
        stage('Get AKS Credentials') {
            steps {
                sh "az aks get-credentials --resource-group ${env.RESOURCE_GROUP} --name ${env.AKS_CLUSTER_NAME} --overwrite-existing"
            }
        }

        stage('ACR Login') {
            steps {
                sh "az acr login --name ${env.ACR_NAME}"
            }
        }

        stage('Build & Push Images') {
            steps {
                script {
                    def services = [
                        'frontend': 'snaplink-web',
                        'api'     : 'snaplink-api',
                        'db'      : 'snaplink-db',
                        'cache'   : 'snaplink-cache'
                    ]

                    services.each { dir, repo ->
                        buildAndPushImage(dir, repo, env.ACR_NAME, env.IMAGE_TAG)
                    }
                }
            }
        }

        stage('Deploy Helm Chart') {
            steps {
                sh """
                    helm upgrade --install snaplink kube/snaplink \
                        --namespace default \
                        --set global.imageRegistry=${env.ACR_NAME}.azurecr.io \
                        --set global.imageTag=${env.IMAGE_TAG} \
                        --set db.user=${env.DB_USER} \
                        --set db.password=${env.DB_PASS}
                """
            }
        }

        stage('Verify Deployment') {
            steps {
                echo "Deployment successfully verified in ${params.ENVIRONMENT} environment."
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo "Application pipeline deployed successfully to ${params.ENVIRONMENT}."
        }
        failure {
            echo "Application pipeline failed for ${params.ENVIRONMENT}."
        }
    }
}

// Function to build and push docker images
def buildAndPushImage(String dir, String repo, String acrName, String tag) {
    echo "Building and pushing ${repo}..."
    sh """
        docker build -t ${acrName}.azurecr.io/${repo}:${tag} src/${dir}
        docker push ${acrName}.azurecr.io/${repo}:${tag}
    """
}
