apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snaplink-db-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bobhatevishal/Helm-deployment-app.git'
    targetRevision: main
    path: helm_charts
    helm:
      valueFiles:
      - ../kube/values/prod/db-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: snaplink-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
