apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snaplink-cache-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bobhatevishal/Helm-deployment-app.git'
    targetRevision: main
    path: helm_charts
    helm:
      valueFiles:
      - ../kube/values/dev/cache-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: snaplink-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
